version: "3.8"

services:
  mysql:
    image: mysql:8.0 
    container_name: hr-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: hr
    volumes:
      - hr_data:/var/lib/mysql

volumes:
  hr_data:
